/**
 * Central export point for all business constants
 */

export {
  LEAD_TIME_WEEKS,
  SPRINGS_PER_PALLET,
  MIN_PALLETS,
  MAX_PALLETS,
  DEFAULT_PALLETS,
  CRITICAL_THRESHOLD,
  TARGET_COVERAGE,
  MIN_COVERAGE_TARGET,
  OVERSTOCK_THRESHOLD,
  MATTRESS_SIZES,
  FIRMNESS_TYPES,
  FIRMNESS_LABELS,
  SPRING_PLANNING_SPLITS,
  COMPONENT_TYPES,
  FELT_TO_SPRING_RATIO,
  KING_QUEEN_ONLY_COMPONENTS,
  SIDE_PANEL_CONSOLIDATED_SIZES,
  NUM_SAVE_SLOTS
} from './springs.js'

export {
  AUSBEDS_EMAIL_DOMAIN,
  ALLOWED_USER_EMAILS
} from './auth.js'

export {
  SEASONAL_DEMAND,
  MONTH_NAMES,
  MONTH_NAMES_FULL,
  getSeasonalMultiplier
} from './shared.js'

export {
  MATTRESS_LATEX_SKUS,
  PILLOW_LATEX_SKUS,
  LATEX_SKUS,
  LATEX_FIRMNESSES,
  LATEX_PLANNING_SPLIT,
  LATEX_SIZES,
  PILLOW_LATEX_TYPES,
  PILLOW_LATEX_LABELS,
  DEFAULT_LATEX_CAPACITY,
  LATEX_CAPACITY_STEP,
  MIN_LATEX_CAPACITY,
  LATEX_LEAD_TIME_WEEKS,
  SIZE_PRIORITY_WEIGHT as LATEX_SIZE_PRIORITY_WEIGHT,
  MIN_COVERAGE_TARGETS as LATEX_MIN_COVERAGE_TARGETS,
  MATTRESS_TO_LATEX_MAP,
  FIRMNESS_LEVEL_RANGES as LATEX_FIRMNESS_LEVEL_RANGES
} from './latex.js'
