/**
 * Central export point for all business constants
 */

export {
  LEAD_TIME_WEEKS,
  SPRINGS_PER_PALLET,
  MIN_PALLETS,
  MAX_PALLETS,
  DEFAULT_PALLETS,
  CRITICAL_THRESHOLD,
  TARGET_COVERAGE,
  MIN_COVERAGE_TARGET,
  OVERSTOCK_THRESHOLD
} from './business.js'

export {
  MATTRESS_SIZES,
  WEEKLY_SALES_RATE,
  SMALL_SIZES,
  HIGH_VELOCITY_SIZES
} from './sales.js'

export {
  FIRMNESS_TYPES,
  FIRMNESS_DISTRIBUTION
} from './firmness.js'

export {
  SEASONAL_DEMAND,
  BUSY_MONTHS,
  SEASONAL_MULTIPLIER_BUSY,
  SEASONAL_MULTIPLIER_SLOW,
  MONTH_NAMES,
  MONTH_NAMES_FULL,
  getSeasonalMultiplier
} from './seasonality.js'

export {
  COMPONENT_TYPES,
  KING_QUEEN_ONLY_COMPONENTS,
  NUM_SAVE_SLOTS
} from './components.js'

export {
  LATEX_SKUS,
  LATEX_FIRMNESSES,
  LATEX_SIZES,
  CONTAINER_40FT,
  CONTAINER_20FT,
  DEFAULT_CONTAINER_SIZE,
  LATEX_LEAD_TIME_WEEKS,
  CONTAINER_CAPACITY,
  SIZE_PRIORITY_WEIGHT as LATEX_SIZE_PRIORITY_WEIGHT,
  MIN_COVERAGE_TARGETS as LATEX_MIN_COVERAGE_TARGETS,
  MATTRESS_TO_LATEX_MAP,
  FIRMNESS_LEVEL_RANGES as LATEX_FIRMNESS_LEVEL_RANGES
} from './latex.js'
